# Generated by Django 3.0.10 on 2021-09-28 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scholar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scholarID', models.CharField(max_length=10)),
                ('scholarName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vase',
            fields=[
                ('vaseRef', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('collectionName', models.CharField(blank=True, max_length=500, null=True)),
                ('previousColl', models.CharField(blank=True, max_length=500, null=True)),
                ('provenanceName', models.CharField(blank=True, max_length=500, null=True)),
                ('height', models.CharField(blank=True, max_length=10, null=True)),
                ('diameter', models.CharField(blank=True, max_length=10, null=True)),
                ('publications', models.CharField(blank=True, max_length=600, null=True)),
                ('subject', models.CharField(blank=True, max_length=800, null=True)),
                ('fabric', models.CharField(blank=True, max_length=50, null=True)),
                ('technique', models.CharField(blank=True, max_length=50, null=True)),
                ('shapeName', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plate',
            fields=[
                ('plateRef', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('vase', models.ManyToManyField(to='api.Vase')),
            ],
        ),
    ]
